import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Header";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=' text-white'
        style={{
          backgroundImage: 'url(background-pic.jpg)',
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
          height: 'full',
          width: 'full',
        }}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
